config/routes.rb
Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new', as: :sign_in
  post 'sign_in', to: 'sessions#create'

  get 'dashboard/index'
  get 'search', to: 'dashboard#search', as: :search

  resources :days, except: [:edit] do
    resources :activities, only: [:create, :destroy], shallow: true
  end

  get 'charts/overall_progress', to: 'charts#overall_progress'
  get 'charts/last', to: 'charts#last'

  root to: 'dashboard#index'

end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :string
#  value       :integer          not null
#  day_id      :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Activity < ActiveRecord::Base
  belongs_to :day

  validates :title, :day_id, :value, presence: true

  after_save    :recalculate_day!
  after_destroy :recalculate_day!

  private

  def recalculate_day!
    self.day.recalculate!
  end
end

app/models/day.rb
# == Schema Information
#
# Table name: days
#
#  id         :integer          not null, primary key
#  day        :date             not null
#  balance    :integer          default(0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Day < ActiveRecord::Base
  has_many :activities

  validates :day, presence: true
  validates :day, uniqueness: true

  before_destroy :delete_activities!

  def recalculate!
    self.balance = activities.sum(:value)
    save!
  end

  def to_s
    day.strftime('%d.%m.%Y')
  end

  # Free of fines days are saturday and sunday
  def free?
    day.wday.in? [0, 6]
  end

  private

  def delete_activities!
    Activity.where(day_id: id).delete_all
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def create
    @day = Day.find(params[:day_id])
    @new_activity = @day.activities.build(activity_params)

    if @new_activity.save
      redirect_to :back #@day
    else
      @activities = @day.activities
      render template: 'days/show'
    end
  end

  def destroy
    activity = Activity.find(params[:id])
    activity.destroy
    redirect_to :back #day_url(activity.day_id)
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :description, :value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :check_authorization

  def check_authorization
    if need_authorization?
      redirect_to sign_in_url
    end
  end

  def need_authorization?
    Rails.env == 'production' and not session[:authorized].in? ['user']
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def overall_progress
    data = [["Day", "Score"]]
    render json: data.concat(day_data)
  end

  def last
    data = [["Day", "Score"]]
    render json: data.concat(day_data(from: params[:days].to_i.days.ago))
  end

  private

  def day_data(from: nil)
    if from
      sum = 100 + Day.where('day <= ?', from).sum(:balance)
      days = Day.where('day > ?', from).order(:day)
    else
      sum = 100
      days = Day.order(:day)
    end

    result = []
    days.each { |day| result << [day.day.to_s, sum += day.balance] }
    result
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    # Today's
    @today = Day.find_by(day: Time.zone.today) || Day.create(day: Time.zone.today)
    @activities = @today.activities.order(:id)
    @total_balance = 100 + Day.all.sum(:balance)

    # Last days
    @decade = Day.order(day: :desc).limit(10)
  end

  def search
    query       = "%" << params[:searchline].mb_chars.downcase.to_s << "%"
    @activities = Activity.where('lower(title) like :q OR lower(description) like :q', q: query)
                          .includes(:day).order(day_id: :desc, id: :asc)
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @days = Day.all.order(day: :desc).limit(25)
  end

  def show
    @day = Day.find(params[:id])
    @new_activity = @day.activities.build
    @activities = @day.activities.order(:id)
  end

  def new
    @day = Day.new
  end

  def create
    @day = Day.new(day_params)
    if @day.save
      redirect_to days_url
    else
      render :new
    end
  end

  def destroy
    Day.find(params[:id]).destroy
    redirect_to days_url
  end

  private

  def day_params
    params.require(:day).permit(:day, :balance)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_authorization

  def new
  end

  def create
    if params[:username] == ENV['CREDENTIALS_USERNAME'] && params[:password] == ENV['CREDENTIALS_PASSWORD']
      session[:authorized] = 'user'
      redirect_to root_url
    else
      session.delete(:authorized)
      redirect_to sign_in_url
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdownify(content)
    pipeline = HTML::Pipeline.new [
      HTML::Pipeline::MarkdownFilter,
      HTML::Pipeline::SanitizationFilter
    ], { gfm: true }

    # Make all links to open in new tab
    result = pipeline.call(content)[:output]
    result.xpath('.//a').each do |link|
      link[:target] = '_blank'
    end

    result.to_s.html_safe
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/activities/_upwork_money_modal_form.html.erb
<!-- Modal! -->
<div class="modal fade" id="upwork_money_modal_form" tabindex="-1" role="dialog" aria-labelledby="account-formLabel">


  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="account-formLabel">Помогу 😖</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-3">
            <%= label_tag :upwork_hours, "Часы" %>
            <%= text_field_tag :upwork_hours, "", class: "form-control", placeholder: "Часы" %>
          </div>
          <div class="col-sm-3">
            <%= label_tag :upwork_hours, "Минуты" %>
            <%= text_field_tag :upwork_minutes, "0", class: "form-control", placeholder: "Минуты" %>
          </div>
          <div class="col-sm-3">
            <%= label_tag :upwork_hours, "Ставка" %>
            <%= text_field_tag :upwork_rate, ENV['my_current_rate'], class: "form-control" %>
          </div>
          <div class="col-sm-3">
            <%= label_tag :upwork_hours, "Кэф" %>
            <%= text_field_tag :upwork_my, ENV['my_portion'], class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button id="write_money" class='btn btn-primary btn-inline' "data-process_on_submit"='true' >
          $0
        </button>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_search_form.html.erb
<div class="row" id="search-form">
  <div class="col-md-12">
    <%= form_tag search_path, method: :get do |f| %>
      <div class="input-group stylish-input-group">
        <%= text_field_tag :searchline, nil, class: 'form-control', placeholder: 'Search' %>
        <span class="input-group-addon">
          <button type="submit">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="jumbotron">
      <h4>Overall</h4>
      <p><%= @total_balance %></p>
    </div>
  </div>
  <div class="col-md-6">
    <div class="jumbotron">
      <h4>Today: <%= @today %></h4>
      <p><%= @today.balance %></p>
    </div>
  </div>
</div>

<%= render partial: 'search_form' %>

<div class="row">
  <section class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%= form_for [@today, @today.activities.build], class: 'form-inline' do |f| %>
              <%= f.text_field :title, placeholder: 'Title' %>
              <%= f.text_field :description, placeholder: 'Description' %>
              <%= f.text_field :value, placeholder: 'Value', value: 2 %>
              <%= f.submit 'Add activity', class: "btn btn-success btn-sm" %>

              <a class="btn btn-default btn-sm" data-toggle="modal" data-target="#upwork_money_modal_form">
                Бабки дня
              </a>
            <% end %>
            <table class="table">
              <thead>
                <th>Title</th>
                <th>Description</th>
                <th>Value</th>
                <th></th>
              </thead>
              <tbody>
                <% @activities.each do |activity| %>
                  <% next unless activity.id %>
                  <tr>
                    <td><%= markdownify activity.title %></td>
                    <td><%= markdownify activity.description %></td>
                    <td><%= activity.value %></td>
                    <td><%= link_to 'Delete', activity, method: :delete %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<div class="row">
  <section class="col-md-3">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <%= link_to days_path do %>
          <h3 class="panel-title">Recent days</h3>
        <% end %>
      </div>
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <th></th>
            <th></th>
          </thead>
          <tbody>
            <% @decade.each do |day| %>
              <tr class="<%= "active" if day.free? %>">
                <td><%= link_to day, day %></td>
                <td><%= day.balance %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </section>

  <section class="col-md-9">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">Graph</h3>
      </div>
      <div class="panel-body">
        <%#= line_chart charts_overall_progress_path, explorer: { actions: ['dragToZoom', 'rightClickToReset'] } %>
        <div id="four-weeks-chart" style="height: 300px;"></div>
        <div id="overall-progress-chart" style="height: 500px;"></div>
      </div>
    </div>
  </section>
</div>

<%= render 'activities/upwork_money_modal_form' %>

app/views/dashboard/search.html.erb
<%= render partial: 'search_form' %>

<table class="table">
  <thead>
    <th>Title</th>
    <th>Description</th>
    <th>Score</th>
    <th>Day</th>
  </thead>
  <tbody>
    <% @activities.each do |activity| %>
      <% next unless activity.id %>
      <tr>
        <td><%= markdownify activity.title %></td>
        <td><%= markdownify activity.description %></td>
        <td><%= activity.value %></td>
        <td><%= link_to activity.day, day_path(activity.day), target: '_blank' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/days/index.html.erb
<h1>Days#index</h1>
<%= link_to 'New day', new_day_path %>
<table class="table">
  <thead>
    <th>Day</th>
    <th>Balance</th>
    <th></th>
  </thead>
  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= link_to(day.day, day) %></td>
        <td><%= day.balance %></td>
        <td><%= link_to 'Delete', day, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New day', new_day_path %>

app/views/days/new.html.erb
<h1>New day</h1>
<%= form_for @day do |f| %>
  <%= f.date_field :day, value: Time.zone.today, autofocus: true %>
  <%= f.text_field :balance %>
  <%= f.submit %>
<% end %>

app/views/days/show.html.erb
<h1>Day <%= @day.day %></h1>

<section>
  <h3>Add new activity</h3>
  <%= form_for [@day, @new_activity] do |f| %>
    <%= f.text_field :title, placeholder: 'Title' %>
    <%= f.text_field :description, placeholder: 'Description' %>
    <%= f.text_field :value, placeholder: 'Value', value: 2 %>

    <%= f.submit 'Add activity', class: "btn btn-success btn-sm" %>
    <a class="btn btn-default btn-sm" data-toggle="modal" data-target="#upwork_money_modal_form">
      Бабки дня
    </a>
  <% end %>
</section>

<section>
  <table class="table">
    <thead>
      <th>Title</th>
      <th>Description</th>
      <th>Value</th>
      <th></th>
    </thead>
    <tbody>
      <% @activities.each do |activity| %>
        <% next unless activity.id %>
        <tr>
          <td><%= markdownify activity.title %></td>
          <td><%= markdownify activity.description %></td>
          <td><%= activity.value %></td>
          <td><%= link_to 'Delete', activity, method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

<%= render 'activities/upwork_money_modal_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProgressDepth</title>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js", 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

  <%= yield %>

</body>
</html>